# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buatakun.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_buat_akun_Form(object):
    def setupUi(self, buat_akun_Form):
        buat_akun_Form.setObjectName("buat_akun_Form")
        buat_akun_Form.resize(975, 823)
        buat_akun_Form.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label = QtWidgets.QLabel(buat_akun_Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 90, 961, 141))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size:28pt;\n"
"text-allign: center;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(buat_akun_Form)
        self.label_2.setGeometry(QtCore.QRect(150, 340, 151, 71))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 15pt;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(buat_akun_Form)
        self.label_3.setGeometry(QtCore.QRect(150, 420, 151, 71))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 15pt;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(buat_akun_Form)
        self.username.setGeometry(QtCore.QRect(350, 350, 311, 51))
        self.username.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);\n"
"padd")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(buat_akun_Form)
        self.password.setGeometry(QtCore.QRect(350, 430, 311, 51))
        self.password.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);\n"
"padd")
        self.password.setText("")
        self.password.setObjectName("password")
        self.registerbutton = QtWidgets.QPushButton(buat_akun_Form)
        self.registerbutton.setGeometry(QtCore.QRect(450, 670, 101, 41))
        self.registerbutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 14pt;")
        self.registerbutton.setObjectName("registerbutton")
        self.label_4 = QtWidgets.QLabel(buat_akun_Form)
        self.label_4.setGeometry(QtCore.QRect(90, 490, 211, 71))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 15pt;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.confirm_password = QtWidgets.QLineEdit(buat_akun_Form)
        self.confirm_password.setGeometry(QtCore.QRect(350, 500, 311, 51))
        self.confirm_password.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);\n"
"padd")
        self.confirm_password.setText("")
        self.confirm_password.setObjectName("confirm_password")
        self.kembalibutton = QtWidgets.QPushButton(buat_akun_Form)
        self.kembalibutton.setGeometry(QtCore.QRect(200, 670, 101, 41))
        self.kembalibutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 14pt;")
        self.kembalibutton.setObjectName("kembalibutton")
        self.responseregtext = QtWidgets.QLabel(buat_akun_Form)
        self.responseregtext.setGeometry(QtCore.QRect(360, 570, 581, 61))
        self.responseregtext.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Myanmar Text\";")
        self.responseregtext.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.responseregtext.setWordWrap(True)
        self.responseregtext.setObjectName("responseregtext")

        self.retranslateUi(buat_akun_Form)
        QtCore.QMetaObject.connectSlotsByName(buat_akun_Form)

    def retranslateUi(self, buat_akun_Form):
        _translate = QtCore.QCoreApplication.translate
        buat_akun_Form.setWindowTitle(_translate("buat_akun_Form", "Form"))
        self.label.setText(_translate("buat_akun_Form", "Register"))
        self.label_2.setText(_translate("buat_akun_Form", "Username"))
        self.label_3.setText(_translate("buat_akun_Form", "Password"))
        self.username.setPlaceholderText(_translate("buat_akun_Form", "Masukkan Username"))
        self.password.setPlaceholderText(_translate("buat_akun_Form", "Masukkan Password"))
        self.registerbutton.setText(_translate("buat_akun_Form", "Register"))
        self.label_4.setText(_translate("buat_akun_Form", "Confirm Password"))
        self.confirm_password.setPlaceholderText(_translate("buat_akun_Form", "Confirm Password"))
        self.kembalibutton.setText(_translate("buat_akun_Form", "Kembali"))
        self.responseregtext.setText(_translate("buat_akun_Form", "TextLabel"))
