# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_form(object):
    def setupUi(self, home_form):
        home_form.setObjectName("home_form")
        home_form.resize(975, 823)
        home_form.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label = QtWidgets.QLabel(home_form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 981, 151))
        self.label.setStyleSheet("color: rgb(255,255,255);\n"
"background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);\n"
"font-size:28pt;\n"
"text-allign: center;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(home_form)
        self.label_3.setGeometry(QtCore.QRect(160, 170, 151, 71))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 15pt;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.datasuhu = QtWidgets.QLineEdit(home_form)
        self.datasuhu.setGeometry(QtCore.QRect(360, 180, 311, 51))
        self.datasuhu.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);\n"
"padd")
        self.datasuhu.setText("")
        self.datasuhu.setObjectName("datasuhu")
        self.suhusubmitbutton = QtWidgets.QPushButton(home_form)
        self.suhusubmitbutton.setGeometry(QtCore.QRect(450, 270, 101, 41))
        self.suhusubmitbutton.setAutoFillBackground(False)
        self.suhusubmitbutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 14pt;")
        self.suhusubmitbutton.setObjectName("suhusubmitbutton")
        self.groupBox = QtWidgets.QGroupBox(home_form)
        self.groupBox.setGeometry(QtCore.QRect(750, 0, 221, 151))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_2.setStyleSheet("font-size:11pt;")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_4.setStyleSheet("font-size: 11pt;")
        self.label_4.setObjectName("label_4")
        self.usernameaccount = QtWidgets.QLabel(self.groupBox)
        self.usernameaccount.setGeometry(QtCore.QRect(100, 30, 101, 21))
        self.usernameaccount.setStyleSheet("font-size: 11pt;")
        self.usernameaccount.setObjectName("usernameaccount")
        self.Id_account = QtWidgets.QLabel(self.groupBox)
        self.Id_account.setGeometry(QtCore.QRect(100, 50, 91, 21))
        self.Id_account.setStyleSheet("font-size:11pt;")
        self.Id_account.setObjectName("Id_account")
        self.Logoutbutton = QtWidgets.QPushButton(self.groupBox)
        self.Logoutbutton.setGeometry(QtCore.QRect(60, 110, 93, 28))
        self.Logoutbutton.setObjectName("Logoutbutton")
        self.label_5 = QtWidgets.QLabel(home_form)
        self.label_5.setGeometry(QtCore.QRect(400, 340, 191, 71))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size : 14pt;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.tablemonitoringWidget = QtWidgets.QTableWidget(home_form)
        self.tablemonitoringWidget.setGeometry(QtCore.QRect(200, 410, 600, 350))
        self.tablemonitoringWidget.setMouseTracking(False)
        self.tablemonitoringWidget.setObjectName("tablemonitoringWidget")
        self.tablemonitoringWidget.setColumnCount(4)
        self.tablemonitoringWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablemonitoringWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablemonitoringWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablemonitoringWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablemonitoringWidget.setHorizontalHeaderItem(3, item)
        self.tablemonitoringWidget.horizontalHeader().setCascadingSectionResizes(False)

        self.retranslateUi(home_form)
        QtCore.QMetaObject.connectSlotsByName(home_form)

    def retranslateUi(self, home_form):
        _translate = QtCore.QCoreApplication.translate
        home_form.setWindowTitle(_translate("home_form", "Form"))
        self.label.setText(_translate("home_form", "MONITORING"))
        self.label_3.setText(_translate("home_form", "Suhu"))
        self.datasuhu.setPlaceholderText(_translate("home_form", "Masukkan Suhu"))
        self.suhusubmitbutton.setText(_translate("home_form", "Submit"))
        self.groupBox.setTitle(_translate("home_form", "Account"))
        self.label_2.setText(_translate("home_form", "Username"))
        self.label_4.setText(_translate("home_form", "ID"))
        self.usernameaccount.setText(_translate("home_form", "TextLabel"))
        self.Id_account.setText(_translate("home_form", "TextLabel"))
        self.Logoutbutton.setText(_translate("home_form", "Logout"))
        self.label_5.setText(_translate("home_form", "Data Monitoring"))
        item = self.tablemonitoringWidget.horizontalHeaderItem(0)
        item.setText(_translate("home_form", "Ruangan"))
        item = self.tablemonitoringWidget.horizontalHeaderItem(1)
        item.setText(_translate("home_form", "Suhu"))
        item = self.tablemonitoringWidget.horizontalHeaderItem(2)
        item.setText(_translate("home_form", "Waktu"))
        item = self.tablemonitoringWidget.horizontalHeaderItem(3)
        item.setText(_translate("home_form", "Auto/Manual"))
